# fly.toml app configuration file generated for restless-surf-4583 on 2023-08-31T07:44:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-surf-4583"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
